name = "GeoStatsImages"
uuid = "7cd16168-b42c-5e7d-a585-4f59d326662d"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.3.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "≥ 1.0.0"
